database:
  host: localhost
  port: 5432
  database_name: persephone
  user: persephone
  password: ""
matrix:
  server_name: localhost
  server_key_location: ./server_key.key
webserver:
  ssl: false

log_level: debug
